version: "3"

services:
  spring_boot_app:
    image: ggramgyo/decode-hub:backend
    container_name: decode-server
    ports:
      - "7777:7777"
    volumes:
      - ./application.yml:/app/config/application.yml
      - ./decode.p12:/app/config/decode.p12
  dockerhub-login:
    image: alpine
    entrypoint: /bin/sh
    command: -c "echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin"

  redis:
    image: redis
    container_name: redis
    hostname: redis
    command: redis-server --requirepass $REDIS_PASSWORD --port 6379
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
